(function(g){
'use strict';
var core=g.UrbeCore,docs=core&&core.service('documents'),store=core&&core.service('compositions');if(!core||!docs||!store)return;
function esc(s){return String(s==null?'':s).replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]))}
function attr(s){return esc(s).replace(/'/g,'&#39;')}
function url(s,image){s=String(s||'').trim();if(!s||/[\u0000-\u001f]/.test(s))return '#';if(/^[a-z][\w+.-]*:/i.test(s)&&!(/^(https?:|mailto:)/i.test(s)||(image&&/^data:image\/(png|jpeg|gif|webp);base64,/i.test(s))))return '#';return s}
function inline(v){var images=[],s=esc(v);s=s.replace(/!\[([^\]]*)\]\(([^)]+)\)/g,(_,label,src)=>{images.push('<img alt="'+attr(label)+'" src="'+attr(url(src,true))+'">');return'\u0001'+(images.length-1)+'\u0002'});s=s.replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,label,href)=>'<a href="'+attr(url(href,false))+'">'+label+'</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g,(_,target,label)=>'<a href="#" data-wikilink="'+attr(target)+'">'+(label||target)+'</a>');return s.replace(/\u0001(\d+)\u0002/g,(_,i)=>images[Number(i)])}
function parse(src,docId){var lines=String(src||'').replace(/\r\n?/g,'\n').split('\n'),nodes=[],para=[],i=0;if(lines[0]==='---'){var end=lines.indexOf('---',1);if(end>0)i=end+1}function push(type,html){nodes.push({id:String(docId)+'_'+nodes.length,type,html})}function flush(){if(para.length){push('paragraph','<p>'+inline(para.join(' '))+'</p>');para=[]}}
while(i<lines.length){var line=lines[i],h=line.match(/^(#{1,6})\s+(.+)/);if(!line.trim()){flush();i++;continue}if(/^```/.test(line)){flush();var lang=line.slice(3).trim().replace(/[^\w-]/g,''),code=[];i++;while(i<lines.length&&!/^```/.test(lines[i]))code.push(lines[i++]);if(i<lines.length)i++;push('code','<pre><code'+(lang?' class="language-'+attr(lang)+'"':'')+'>'+esc(code.join('\n'))+'</code></pre>');continue}if(h){flush();push('heading','<h'+h[1].length+'>'+inline(h[2])+'</h'+h[1].length+'>');i++;continue}if(/^>\s?/.test(line)){flush();push('blockquote','<blockquote>'+inline(line.replace(/^>\s?/,''))+'</blockquote>');i++;continue}if(/^!\[[^\]]*\]\([^)]+\)\s*$/.test(line.trim())){flush();push('image','<figure>'+inline(line.trim())+'</figure>');i++;continue}if(/^[-*+]\s+/.test(line)||/^\d+[.)]\s+/.test(line)){flush();var ordered=/^\d/.test(line),re=ordered?/^\d+[.)]\s+/:/^[-*+]\s+/,items=[];while(i<lines.length&&re.test(lines[i]))items.push('<li>'+inline(lines[i++].replace(re,''))+'</li>');push('list','<'+(ordered?'ol':'ul')+'>'+items.join('')+'</'+(ordered?'ol':'ul')+'>');continue}if(/^\|.*\|$/.test(line)&&/^\|?[\s:|-]+\|?$/.test(lines[i+1]||'')){flush();var heads=line.split('|').slice(1,-1),rows=[];i+=2;while(i<lines.length&&/^\|.*\|$/.test(lines[i]))rows.push(lines[i++].split('|').slice(1,-1));push('table','<table><thead><tr>'+heads.map(x=>'<th>'+inline(x.trim())+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+inline(x.trim())+'</td>').join('')+'</tr>').join('')+'</tbody></table>');continue}para.push(line.trim());i++}flush();return nodes}
function cssDecl(o){var map={fontFamily:'font-family',fontSize:'font-size',lineHeight:'line-height',color:'color',background:'background',textAlign:'text-align',marginTop:'margin-top',marginBottom:'margin-bottom',padding:'padding',maxWidth:'max-width'};return Object.keys(o||{}).filter(k=>map[k]&&o[k]!==''&&o[k]!=null).map(k=>{var v=o[k];if(['fontSize','marginTop','marginBottom','padding','maxWidth'].includes(k)&&typeof v==='number')v=v+'px';return map[k]+':'+String(v).replace(/[;{}<>]/g,'')}).join(';')}
function num(x,f,min,max){var n=Number(x);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):f}
function compile(id){var x=store.get(id);if(!x)throw Error('Composição não encontrada');if(x.htmlSource)return x.htmlSource;var sources=x.order&&x.order.length?x.order:x.sources,overrides=x.overrides||{},rules=[];var body=sources.map(function(docId,index){var doc=docs.get(docId);if(!doc)return'';return'<section class="urbe-source" data-document-id="'+attr(doc.id)+'" data-source-index="'+index+'">'+parse(doc.content,doc.id).map(function(node){var rule=cssDecl(overrides[node.id]);if(rule)rules.push('[data-node-id="'+attr(node.id)+'"]{'+rule+'}');return'<div class="urbe-node" data-node-id="'+attr(node.id)+'" data-node-type="'+node.type+'">'+node.html+'</div>'}).join('\n')+'</section>'}).join('\n');var st=x.styles||{},families=String(st.fontFamily||'Georgia, serif').split(',').map(s=>JSON.stringify(s.trim().replace(/[<>;{}]/g,''))).join(',');var css=':root{--font-body:'+families+';--font-size:'+num(st.fontSize,18,8,160)+'px;--line:'+num(st.lineHeight,1.65,.8,4)+';--text:'+String(st.color||'#202020').replace(/[;{}<>]/g,'')+';--paper:'+String(st.background||'#fff').replace(/[;{}<>]/g,'')+';--width:'+num(st.maxWidth,760,120,1800)+'px}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--text);font-family:var(--font-body);font-size:var(--font-size);line-height:var(--line);text-align:'+(['left','center','right','justify'].includes(st.textAlign)?st.textAlign:'left')+'}main{max-width:var(--width);margin:auto;padding:'+num(st.padding,48,0,240)+'px 24px 96px}img{max-width:100%;height:auto}h1,h2,h3{line-height:1.15}.urbe-node{position:relative}.urbe-node> :first-child{margin-top:0}.urbe-node> :last-child{margin-bottom:1em}blockquote{border-left:3px solid currentColor;padding-left:1em;opacity:.82}.urbe-source+.urbe-source{margin-top:4rem}table{border-collapse:collapse;width:100%}td,th{border:1px solid #aaa;padding:.4em}'+rules.join('')+String(x.customCSS||'').replace(/[<>]/g,'');return'<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(x.name)+'</title><style>'+css+'</style></head><body><main>'+body+'</main></body></html>'}
core.events.on('document:updated',function(event){if(!event.previous||event.previous.content===event.document.content)return;var old=parse(event.previous.content,event.document.id),next=parse(event.document.content,event.document.id);store.list().filter(x=>x.sources.includes(event.document.id)).forEach(function(composition){var before=composition.overrides||{},after={...before},claimed=new Set(),changed=false;old.forEach(function(node,index){if(!before[node.id])return;var match=next.findIndex((n,j)=>!claimed.has(j)&&n.type===node.type&&n.html===node.html);if(match<0&&next[index]&&next[index].type===node.type&&!claimed.has(index))match=index;if(match<0)return;claimed.add(match);if(match!==index){delete after[node.id];after[next[match].id]=before[node.id];changed=true}});if(changed)store.update(composition.id,{overrides:after})})});
var api={parse,markdown:src=>parse(src,'preview').map(n=>n.html).join('\n'),compile};core.provide('composition.compiler',api);core.commands.register('composition.compile',{title:'Compilar HTML',category:'Produção',execute:x=>compile(x.id)});g.UrbeCompositionCompiler=api;
})(window);
