(function(g){'use strict';var c=g.UrbeCore,docs=c&&c.service('documents'),store=c&&c.service('compositions');if(!c||!docs||!store)return;
function esc(s){return String(s==null?'':s).replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]))}
function attr(s){return esc(s).replace(/'/g,'&#39;')}
function inline(s){return esc(s).replace(/!\[([^\]]*)\]\(([^)]+)\)/g,'<img alt="$1" src="$2">').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g,function(_,target,label){return'<a href="#" data-wikilink="'+attr(target)+'">'+esc(label||target)+'</a>'})}
function parse(src,docId){var nodes=[],para=[],pi=0;function push(type,html){nodes.push({id:String(docId)+'_'+(pi++),type:type,html:html})}function flush(){if(para.length){push('paragraph','<p>'+inline(para.join(' '))+'</p>');para=[]}}
String(src||'').split(/\r?\n/).forEach(function(l){var h=l.match(/^(#{1,6})\s+(.+)/);if(h){flush();push('heading','<h'+h[1].length+'>'+inline(h[2])+'</h'+h[1].length+'>')}else if(/^>\s?/.test(l)){flush();push('blockquote','<blockquote>'+inline(l.replace(/^>\s?/,''))+'</blockquote>')}else if(/^[-*]\s+/.test(l)){flush();push('list-item','<div class="urbe-list-item">• '+inline(l.replace(/^[-*]\s+/,''))+'</div>')}else if(/^!\[[^\]]*\]\([^)]+\)\s*$/.test(l.trim())){flush();push('image','<figure>'+inline(l.trim())+'</figure>')}else if(!l.trim())flush();else para.push(l.trim())});flush();return nodes}
function cssDecl(o){o=o||{};var map={fontFamily:'font-family',fontSize:'font-size',lineHeight:'line-height',color:'color',background:'background',textAlign:'text-align',marginTop:'margin-top',marginBottom:'margin-bottom',padding:'padding',maxWidth:'max-width'};return Object.keys(o).filter(k=>map[k]&&o[k]!==''&&o[k]!=null).map(function(k){var v=o[k];if(['fontSize','marginTop','marginBottom','padding','maxWidth'].includes(k)&&typeof v==='number')v=v+'px';return map[k]+':'+v}).join(';')}
function compile(id){var x=store.get(id);if(!x)throw Error('Composição não encontrada');var ss=(x.order&&x.order.length?x.order:x.sources)||[],ov=x.overrides||{},rules=[];var body=ss.map(function(did,i){var d=docs.get(did);if(!d)return'';var nodes=parse(d.content,d.id);return'<section class="urbe-source" data-document-id="'+attr(d.id)+'" data-source-index="'+i+'">'+nodes.map(function(n){var decl=cssDecl(ov[n.id]);if(decl)rules.push('[data-node-id="'+n.id+'"]{'+decl+'}');return'<div class="urbe-node" data-node-id="'+attr(n.id)+'" data-node-type="'+n.type+'">'+n.html+'</div>'}).join('\n')+'</section>'}).join('\n');
var st=x.styles||{},css=':root{--font-body:'+JSON.stringify(st.fontFamily||'Georgia, serif')+';--font-size:'+(st.fontSize||18)+'px;--line:'+(st.lineHeight||1.65)+';--text:'+(st.color||'#202020')+';--paper:'+(st.background||'#fff')+';--width:'+(st.maxWidth||760)+'px}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--text);font-family:var(--font-body);font-size:var(--font-size);line-height:var(--line)}main{max-width:var(--width);margin:auto;padding:'+(st.padding==null?48:st.padding)+'px 24px 96px}img{max-width:100%;height:auto}h1,h2,h3{line-height:1.15}.urbe-node{position:relative}.urbe-node> :first-child{margin-top:0}.urbe-node> :last-child{margin-bottom:1em}blockquote{border-left:3px solid currentColor;padding-left:1em;opacity:.82}.urbe-source+.urbe-source{margin-top:4rem}.urbe-list-item{margin:.3em 0}'+rules.join('')+(x.customCSS||'');
return'<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(x.name)+'</title><style>'+css+'</style></head><body><main>'+body+'</main></body></html>'}
var api={parse:parse,markdown:function(src){return parse(src,'preview').map(n=>n.html).join('\n')},compile:compile};c.provide('composition.compiler',api);c.commands.register('composition.compile',{title:'Compilar HTML',category:'Produção',execute:x=>compile(x.id)});g.UrbeCompositionCompiler=api;})(window);