(function(g){
'use strict';
var core=g.UrbeCore,store=core&&core.service('compositions'),compiler=core&&core.service('composition.compiler'),docs=core&&core.service('documents');if(!core||!store||!compiler)return;
var root,active=null,selected=null,codeMode=false,codeKind='css',renderVersion=0;
function escape(v){var d=document.createElement('div');d.textContent=String(v==null?'':v);return d.innerHTML}
function ensure(){if(root)return;root=document.createElement('section');root.id='compositionWorkspace';root.hidden=true;root.innerHTML='<header><button data-back aria-label="Voltar">←</button><strong data-title>Composição</strong><div><button data-rename title="Renomear">✎</button><button data-code>CSS</button><button data-html>HTML</button><button data-export>Exportar</button></div></header><div class="cmp-body"><aside class="cmp-sources"></aside><div class="cmp-stage"><iframe sandbox="allow-same-origin" title="Prévia da composição"></iframe><div class="cmp-code-wrap" hidden><div><button data-apply-code>Aplicar</button><button data-reset-html hidden>Voltar ao gerado</button><small data-code-label></small></div><textarea class="cmp-code" spellcheck="false"></textarea></div></div><aside class="cmp-inspector"><h3 data-inspector-title>Documento</h3><label>Fonte<input data-style="fontFamily" placeholder="Georgia, serif"></label><label>Tamanho<input data-style="fontSize" type="number" min="8" max="160"></label><label>Entrelinha<input data-style="lineHeight" type="number" min=".8" max="4" step=".05"></label><label>Cor<input data-style="color" type="color"></label><label>Fundo<input data-style="background" type="color"></label><label>Alinhamento<select data-style="textAlign"><option value="">Padrão</option><option value="left">Esquerda</option><option value="center">Centro</option><option value="right">Direita</option><option value="justify">Justificado</option></select></label><label>Largura<input data-style="maxWidth" type="number" min="120" max="1800"></label><label>Espaçamento<input data-style="padding" type="number" min="0" max="240"></label><button data-clear-style>Limpar estilo do elemento</button></aside></div>';document.body.appendChild(root);
root.querySelector('[data-back]').onclick=close;root.querySelector('[data-rename]').onclick=rename;root.querySelector('[data-code]').onclick=()=>toggleCode('css');root.querySelector('[data-html]').onclick=()=>toggleCode('html');root.querySelector('[data-export]').onclick=download;root.querySelector('[data-apply-code]').onclick=applyCode;root.querySelector('[data-reset-html]').onclick=resetHTML;root.querySelector('[data-clear-style]').onclick=clearNode;root.querySelectorAll('[data-style]').forEach(el=>el.oninput=()=>style(el.dataset.style,el.value))}
function setMode(mode){codeMode=!!mode;if(mode)codeKind=mode;root.querySelector('iframe').hidden=codeMode;root.querySelector('.cmp-code-wrap').hidden=!codeMode;root.querySelector('.cmp-inspector').hidden=codeMode||!!store.get(active)?.htmlSource;if(codeMode){var x=store.get(active);root.querySelector('.cmp-code').value=codeKind==='html'?(x.htmlSource||compiler.compile(active)):x.customCSS||'';root.querySelector('[data-code-label]').textContent=codeKind==='html'?'Código HTML completo':'CSS personalizado';root.querySelector('[data-reset-html]').hidden=codeKind!=='html'||!x.htmlSource}}
function open(id){ensure();if(!store.get(id))return false;active=id;selected=null;root.hidden=false;setMode(false);render();return true}
function close(){if(root)root.hidden=true;selected=null;active=null}
async function rename(){var x=store.get(active),name=await g.UrbeDialogs.prompt({title:'Renomear composição',label:'Nome',value:x.name,confirm:'Renomear'});if(name&&name.trim()){store.update(active,{name:name.trim()});render()}}
function sources(x){var order=x.order&&x.order.length?x.order:x.sources;root.querySelector('.cmp-sources').innerHTML='<h3>Fontes</h3>'+order.map((id,i)=>{var doc=docs.get(id);return doc?'<div class="cmp-source"><span>'+escape(doc.title)+'</span><small>'+escape(doc.path)+'</small><div><button data-up="'+i+'" '+(i?'':'disabled')+'>↑</button><button data-down="'+i+'" '+(i===order.length-1?'disabled':'')+'>↓</button></div></div>':'<div class="cmp-source">Fonte indisponível: '+escape(id)+'</div>'}).join('');root.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>move(Number(b.dataset.up),-1));root.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>move(Number(b.dataset.down),1))}
function fileData(blob){return new Promise((resolve,reject)=>{var reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)})}
async function materializeImages(html){var persistence=core.service('persistence');if(!persistence||!persistence.adapter||!persistence.adapter.readBlob||!persistence.vault||!/<img\b/i.test(html))return html;var dom=new DOMParser().parseFromString(html,'text/html');var images=dom.querySelectorAll('section[data-document-id] img[src]');for(const image of images){var src=image.getAttribute('src');if(!src||/^(?:https?:|data:|#|\/)/i.test(src))continue;var section=image.closest('[data-document-id]'),doc=docs.get(section.dataset.documentId);if(!doc)continue;var base=doc.path.split('/');base.pop();var parts=base.concat(src.split('/'));var safe=[];for(const part of parts){if(part==='..')safe.pop();else if(part&&part!=='.')safe.push(part)}try{var blob=await persistence.adapter.readBlob(persistence.vault,safe.join('/'));if(blob)image.src=await fileData(blob)}catch(error){console.warn('Imagem indisponível na composição',src,error)}}return '<!doctype html>\n'+dom.documentElement.outerHTML}
async function render(){var x=store.get(active);if(!x||!root||root.hidden)return;root.querySelector('[data-title]').textContent=x.name;sources(x);var version=++renderVersion,html=await materializeImages(compiler.compile(active));if(version!==renderVersion||root.hidden)return;var frame=root.querySelector('iframe');frame.srcdoc=html;frame.onload=function(){var doc=frame.contentDocument;if(!doc)return;doc.querySelectorAll('.urbe-node').forEach(function(node){node.style.cursor='pointer';node.style.outline=node.dataset.nodeId===selected?'2px solid #4cc9f0':'';node.onclick=function(ev){ev.preventDefault();ev.stopPropagation();selected=node.dataset.nodeId;renderInspector();doc.querySelectorAll('.urbe-node').forEach(q=>q.style.outline=q.dataset.nodeId===selected?'2px solid #4cc9f0':'')}});doc.body.onclick=function(){selected=null;renderInspector();doc.querySelectorAll('.urbe-node').forEach(q=>q.style.outline='')}};root.querySelector('.cmp-inspector').hidden=!!x.htmlSource||codeMode;renderInspector()}
function renderInspector(){var x=store.get(active);if(!x)return;var target=selected?(x.overrides&&x.overrides[selected]||{}):x.styles||{};root.querySelector('[data-inspector-title]').textContent=selected?'Elemento selecionado':'Documento';root.querySelectorAll('[data-style]').forEach(function(input){var v=target[input.dataset.style];if(input.type==='color')input.value=v&&/^#[0-9a-f]{6}$/i.test(v)?v:(input.dataset.style==='background'?'#ffffff':'#202020');else input.value=v==null?'':v})}
function style(key,value){var x=store.get(active);if(!x||x.htmlSource)return;var target=selected?{...x.overrides}:{...x.styles},item=selected?{...(target[selected]||{})}:target;item[key]=['fontSize','lineHeight','maxWidth','padding'].includes(key)&&value!==''?Number(value):value;if(selected){target[selected]=item;store.update(active,{overrides:target})}else store.update(active,{styles:item});render()}
function clearNode(){if(!selected)return;var x=store.get(active),next={...x.overrides};delete next[selected];store.update(active,{overrides:next});render()}
function move(index,delta){var x=store.get(active),order=(x.order&&x.order.length?x.order:x.sources).slice(),j=index+delta;if(j<0||j>=order.length)return;[order[index],order[j]]=[order[j],order[index]];store.update(active,{order});render()}
function toggleCode(kind){if(codeMode&&codeKind===kind){setMode(false);render()}else setMode(kind)}
function applyCode(){var value=root.querySelector('.cmp-code').value;if(codeKind==='html'){if(!/^\s*(?:<!doctype\s+html[^>]*>\s*)?<html[\s>]/i.test(value)){g.UrbeDialogs.alert({title:'HTML incompleto',message:'Informe um documento HTML completo, começando por <html>.'});return}store.update(active,{htmlSource:value})}else store.update(active,{customCSS:value});setMode(false);render()}
async function resetHTML(){if(!(await g.UrbeDialogs.confirm({title:'Voltar ao HTML gerado?',message:'As alterações manuais no HTML serão removidas.',confirm:'Voltar ao gerado',danger:true})))return;store.update(active,{htmlSource:''});setMode(false);render()}
async function download(){var x=store.get(active);if(!x)return;var html=await materializeImages(compiler.compile(active)),blob=new Blob([html],{type:'text/html;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(x.name||'composicao').replace(/[^\w\-]+/g,'-')+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function create(ctx){var ids=(ctx&&ctx.ids||[]).filter(id=>docs.get(id));if(!ids.length)return null;var first=docs.get(ids[0]),x=store.create({name:ctx&&ctx.name||(ids.length===1?first.title:'Nova composição'),type:ctx&&ctx.type||'document',sources:ids,order:ids});open(x.id);return x}
core.commands.register('ui.composition.create',{title:'Criar composição',category:'Produção',execute:create});core.commands.register('ui.composition.open',{title:'Abrir composição',category:'Produção',execute:x=>open(x&&x.id)});core.provide('composition.ui',{open,close,create});
})(window);
