(function(g){'use strict';var c=g.UrbeCore,s=c&&c.service('compositions'),cmp=c&&c.service('composition.compiler'),docs=c&&c.service('documents');if(!c||!s||!cmp)return;var root,active=null,selected=null,codeMode=false;
function e(v){var d=document.createElement('div');d.textContent=String(v||'');return d.innerHTML}
function ensure(){if(root)return;root=document.createElement('section');root.id='compositionWorkspace';root.hidden=true;root.innerHTML='<header><button data-back aria-label="Voltar">←</button><strong data-title>Composição</strong><div><button data-code>&lt;/&gt;</button><button data-export>Exportar</button></div></header><div class="cmp-body"><aside class="cmp-sources"></aside><div class="cmp-stage"><iframe sandbox="allow-same-origin"></iframe><div class="cmp-code-wrap" hidden><div><button data-apply-css>Aplicar CSS</button><small>CSS personalizado</small></div><textarea class="cmp-code" spellcheck="false"></textarea></div></div><aside class="cmp-inspector"><h3 data-inspector-title>Documento</h3><label>Fonte<input data-style="fontFamily" placeholder="Georgia, serif"></label><label>Tamanho<input data-style="fontSize" type="number" min="8" max="160"></label><label>Entrelinha<input data-style="lineHeight" type="number" min=".8" max="4" step=".05"></label><label>Cor<input data-style="color" type="color"></label><label>Fundo<input data-style="background" type="color"></label><label>Alinhamento<select data-style="textAlign"><option value="">Padrão</option><option value="left">Esquerda</option><option value="center">Centro</option><option value="right">Direita</option><option value="justify">Justificado</option></select></label><label>Largura<input data-style="maxWidth" type="number" min="120" max="1800"></label><label>Espaçamento<input data-style="padding" type="number" min="0" max="240"></label><button data-clear-style>Limpar estilo do elemento</button></aside></div>';document.body.appendChild(root);root.querySelector('[data-back]').onclick=close;root.querySelector('[data-code]').onclick=toggleCode;root.querySelector('[data-export]').onclick=download;root.querySelector('[data-apply-css]').onclick=applyCSS;root.querySelector('[data-clear-style]').onclick=clearNode;root.querySelectorAll('[data-style]').forEach(x=>x.oninput=()=>style(x.dataset.style,x.value))}
function open(id){ensure();active=id;selected=null;codeMode=false;root.hidden=false;render()}
function close(){if(root)root.hidden=true;selected=null}
function sources(x){root.querySelector('.cmp-sources').innerHTML='<h3>Fontes</h3>'+x.order.map(function(id,i){var d=docs.get(id);return d?'<div class="cmp-source" data-source="'+e(id)+'"><span>'+e(d.title)+'</span><small>'+e(d.path)+'</small><div><button data-up="'+i+'" '+(i?'':'disabled')+'>↑</button><button data-down="'+i+'" '+(i===x.order.length-1?'disabled':'')+'>↓</button></div></div>':''}).join('');root.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>move(Number(b.dataset.up),-1));root.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>move(Number(b.dataset.down),1))}
function render(){var x=s.get(active);if(!x)return;root.querySelector('[data-title]').textContent=x.name;sources(x);var html=cmp.compile(active),fr=root.querySelector('iframe');fr.srcdoc=html;fr.onload=function(){var doc=fr.contentDocument;if(!doc)return;doc.querySelectorAll('.urbe-node').forEach(function(n){n.style.cursor='pointer';if(n.dataset.nodeId===selected)n.style.outline='2px solid #4cc9f0';n.onclick=function(ev){ev.preventDefault();ev.stopPropagation();selected=n.dataset.nodeId;renderInspector();doc.querySelectorAll('.urbe-node').forEach(q=>q.style.outline=q.dataset.nodeId===selected?'2px solid #4cc9f0':'')}});doc.body.onclick=function(){selected=null;renderInspector();doc.querySelectorAll('.urbe-node').forEach(q=>q.style.outline='')}};root.querySelector('.cmp-code').value=x.customCSS||'';renderInspector()}
function renderInspector(){var x=s.get(active),target=selected?(x.overrides&&x.overrides[selected]||{}):x.styles||{};root.querySelector('[data-inspector-title]').textContent=selected?'Elemento selecionado':'Documento';root.querySelectorAll('[data-style]').forEach(function(i){var v=target[i.dataset.style];if(i.type==='color')i.value=v&&/^#[0-9a-f]{6}$/i.test(v)?v:(i.dataset.style==='background'?'#ffffff':'#202020');else i.value=v==null?'':v})}
function style(k,v){var x=s.get(active);if(selected){var ov=Object.assign({},x.overrides),cur=Object.assign({},ov[selected]||{});cur[k]=['fontSize','lineHeight','maxWidth','padding'].includes(k)&&v!==''?Number(v):v;ov[selected]=cur;s.update(active,{overrides:ov})}else{var st=Object.assign({},x.styles);st[k]=['fontSize','lineHeight','maxWidth','padding'].includes(k)&&v!==''?Number(v):v;s.update(active,{styles:st})}render()}
function clearNode(){if(!selected)return;var x=s.get(active),ov=Object.assign({},x.overrides);delete ov[selected];s.update(active,{overrides:ov});render()}
function move(i,d){var x=s.get(active),o=x.order.slice(),j=i+d;if(j<0||j>=o.length)return;var t=o[i];o[i]=o[j];o[j]=t;s.update(active,{order:o});render()}
function toggleCode(){codeMode=!codeMode;root.querySelector('iframe').hidden=codeMode;root.querySelector('.cmp-code-wrap').hidden=!codeMode;root.querySelector('.cmp-inspector').hidden=codeMode}
function applyCSS(){var css=root.querySelector('.cmp-code').value;s.update(active,{customCSS:css});codeMode=false;render();root.querySelector('iframe').hidden=false;root.querySelector('.cmp-code-wrap').hidden=true;root.querySelector('.cmp-inspector').hidden=false}
function download(){var x=s.get(active),blob=new Blob([cmp.compile(active)],{type:'text/html;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(x.name||'composicao').replace(/[^\w\-]+/g,'-')+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function create(ctx){var ids=(ctx&&ctx.ids||[]).filter(id=>docs.get(id));if(!ids.length)return null;var first=docs.get(ids[0]),x=s.create({name:ctx&&ctx.name||(ids.length===1?first.title:'Nova composição'),type:ctx&&ctx.type||'document',sources:ids,order:ids});open(x.id);return x}
c.commands.register('ui.composition.create',{title:'Criar composição',category:'Produção',execute:create});c.commands.register('ui.composition.open',{title:'Abrir composição',category:'Produção',execute:x=>open(x.id)});c.provide('composition.ui',{open:open,close:close,create:create});})(window);