import fs from 'node:fs';import vm from 'node:vm';
const context={window:{}};vm.createContext(context);
for(const file of ['src/core/core.js','src/core/documents.js','src/explorer/model.js','src/explorer/operations.js'])vm.runInContext(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),context);
const core=context.window.UrbeCore,docs=core.service('documents'),ex=core.service('explorer');
docs.replaceAll([{path:'A.md',content:'a'},{path:'Pasta/B.md',content:'b'},{path:'Pasta/Sub/C.md',content:'c'}]);
const tree=ex.tree();if(tree.children.length!==2||tree.children[0].kind!=='folder')throw new Error('tree');
ex.select('A.md','replace');ex.select('Pasta/B.md','toggle');if(ex.selected().length!==2)throw new Error('multi selection');
ex.favorite('A.md',true);if(ex.listFavorites()[0]?.id!=='A.md')throw new Error('favorite');
ex.touchRecent('Pasta/B.md');if(ex.listRecent()[0]?.id!=='Pasta/B.md')throw new Error('recent');
let d=core.commands.execute('explorer.rename',{id:'A.md',name:'Renomeada'});if(!docs.get('Renomeada.md')||docs.get('A.md'))throw new Error('rename');
d=core.commands.execute('explorer.move',{id:'Renomeada.md',folder:'Pasta'});if(!docs.get('Pasta/Renomeada.md'))throw new Error('move');
d=core.commands.execute('explorer.duplicate',{id:'Pasta/B.md'});if(d.content!=='b'||d.id==='Pasta/B.md')throw new Error('duplicate');
core.commands.execute('explorer.delete',{ids:['Pasta/Sub/C.md']});if(docs.get('Pasta/Sub/C.md'))throw new Error('delete');
console.log('OK   explorer tree');console.log('OK   multi selection');console.log('OK   favorites and recent');console.log('OK   rename move duplicate delete');
