import fs from 'node:fs';import vm from 'node:vm';
const context={window:{},Date};vm.createContext(context);
for(const file of ['src/core/artifacts.js','src/core/core.js','src/core/documents.js','src/core/trash.js'])vm.runInContext(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),context);
const core=context.window.UrbeCore,docs=core.service('documents'),trash=core.service('trash');
const d=docs.upsert({path:'Livro/Capitulo.md',content:'texto'});
trash.trash(d.id);if(docs.get(d.id)||trash.list().length!==1)throw new Error('trash');
const restored=trash.restore(d.id);if(restored.id!==d.id||restored.path!==d.path||restored.content!=='texto')throw new Error('restore identity');
trash.trash(d.id);const exported=trash.export();trash.clear();trash.import(exported);if(trash.list()[0]?.document.id!==d.id)throw new Error('trash persistence');
trash.purge(d.id);if(trash.list().length)throw new Error('purge');
console.log('OK   recoverable trash');console.log('OK   trash preserves identity');console.log('OK   trash serialization');
