(function(global){
'use strict';var core=global.UrbeCore;if(!core)return;
class Diagnostics{
 snapshot(){var get=n=>{try{return core.service(n)}catch(_){return null}},docs=get('documents'),knowledge=get('knowledge'),p=get('persistence'),world=get('aquarium.world'),explorer=get('explorer'),scheduler=get('scheduler');var rt=get('legacy.runtime');return{version:(rt&&rt.version&&rt.version())||core.version||null,timestamp:Date.now(),workspace:p&&p.vault||null,persistence:p?{state:p.state,pending:!!p.pending,busy:!!p.busy,lastSavedAt:p.lastSavedAt}:null,documents:docs?docs.list().length:0,knowledge:knowledge&&knowledge.stats?knowledge.stats():null,aquarium:world?{enabled:world.enabled,entities:world.list().length,links:world.links.length}:null,explorer:explorer&&explorer.snapshot?explorer.snapshot():null,scheduler:scheduler&&scheduler.stats?scheduler.stats():null}}
 verify(){var s=this.snapshot(),issues=[];if(!s.persistence)issues.push('Persistência indisponível');if(!s.knowledge)issues.push('Índice de conhecimento indisponível');if(!s.aquarium)issues.push('Aquário indisponível');if(s.documents&&s.aquarium&&s.aquarium.entities===0)issues.push('Documentos existem, mas nenhuma entidade foi projetada no aquário');return{ok:issues.length===0,issues:issues,state:s}}
}
var d=new Diagnostics();core.provide('diagnostics',d);core.commands.register('workspace.diagnostics',{title:'Diagnóstico do workspace',category:'Workspace',execute:ctx=>{var r=d.verify(),D=global.UrbeDialogs;
  /* chamado pela paleta: mostra o resultado em vez de só devolver os dados */
  if(D&&!(ctx&&ctx.silent)){var st=r.state,p=st.persistence;D.alert({title:r.ok?'Tudo certo':'Diagnóstico',message:(r.ok?'Nenhum problema encontrado.':'Problemas:\n- '+r.issues.join('\n- '))+'\n\nNotas e arquivos: '+st.documents+(st.aquarium?'\nConstruções na cidade: '+st.aquarium.entities+'\nLigações: '+st.aquarium.links:'')+(p?'\nGravação: '+({saved:'salvo',saving:'salvando',dirty:'aguardando',error:'erro',idle:'parado'}[p.state]||p.state)+(p.lastSavedAt?' ('+new Date(p.lastSavedAt).toLocaleTimeString('pt-BR')+')':''):'')+'\nVersão: '+(st.version||'')})}
  return r}});global.UrbeDiagnostics={Diagnostics};
})(window);